// SEARCH
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const SET_SEARCH_RESULTS_SPINNER = 'SET_SEARCH_RESULTS_SPINNER';
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

// MOVIES
export const GET_MOVIES = 'GET_MOVIES';

// INFLIGHT MOVIES
export const RECOMMEND_MOVIE = 'RECOMMEND_MOVIE';
export const RESOLVE_INFLIGHT_MOVIE = 'RESOLVE_INFLIGHT_MOVIE';
export const VOTE = 'VOTE';
export const RESOLVE_INFLIGHT_VOTE = 'RESOLVE_INFLIGHT_VOTE';
export const UNVOTE = 'UNVOTE';
export const RESOLVE_INFLIGHT_UNVOTE = 'RESOLVE_INFLIGHT_UNVOTE';

// USER
export const SET_USER = 'SET_USER';